import Head from 'next/head'
import { Container } from '../components/CommonStyles'
import LoginForm from '../components/Login/Login'
import Footer from '../components/Footer'

export default function Home({ setData }) {
  return (
    <>
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container>
          <LoginForm setData={setData} />
        </Container>
        <Footer />
    </>
  )
}
