import Head from 'next/head'
import { Container } from '../components/CommonStyles'
import Header from '../components/Header'
import LoginForm from '../components/Login/Login'

export default function Home({ data }) {
  return (
    <>
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container>
          <Header data={data} />
          <Container>
            <LoginForm/>
          </Container>
        </Container>
    </>
  )
}
